version: '3'

services:
  proxy:
    build:
      context: ./proxy
    ports:
      - "8082:8082"
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
  database:
    build:
      context: ./database
    container_name: mysql
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
